[package]
name = "vittusave"
version = "0.1.0"
edition = "2024"

[dependencies]
console = "0.15.11"
dialoguer = "0.11.0"
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive", "rc"] }
toml = "0.9.2"
